### PR TITLE
[WIP]Index require issue

### PR DESCRIPTION
**Pull request by danjwinter**
@stevekinney or @rrgayhart 

Edgar and I are still having issues making our index work. We thought it was an issue with our Session class logic but something must have gotten messed up in our file tree and how it is called in the index. In this branch, I distilled index down to requiring a test class and it can't find it when in the debugger. 

I re-cloned the original starter pack and did the same thing here, copying and pasting the code and it works. https://github.com/danjwinter/game-time-starter-kit/tree/index_require_test

The only thing I can think of that might have changed the configuration is the iterator config that we changed for pixel detection. Even when switching to an old branch that worked, we have issues. 

If you change to the branch session, it works only when you start calling the class after requestAnimationFrame runs and you need to do some wonky binding of the session to itself.

Any idea what is going on?

### CODE REVIEW

**Comment by rrgayhart** [comment]
I'm having a hard time parsing what the actual problem is or what code to look at:

The code on this branch works but only if you copy and paste it into a new starter pack?

**Comment by danjwinter** [comment]
Currently the index only has a `const TestClass = require('./test-class')` in it. The test class file is an empty es6 class declaration that is exported.

If you clone this down, run npm install and launch the browser to the index and hit the debugger, It has says TestClass is undefined. 

From what I can tell, the exact same code works on the link I pasted above which is just a blank copy of the starter kit with the same code in the index and the test class. When you clone and run that and hit the same debugger, TestClass is defined.

**Comment by stevekinney** [comment]
Probably not helpful, but it works fine for me.

**Comment by danjwinter** [comment]
Thanks @stevekinney and @rrgayhart for getting back so quickly, especially on the weekend! Meeka was able to help us move forward and today I learned that debugger does not a pry make. And false positives are a pain.

**Pull request closed without merging**
